version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - "3000:3000"
    # depends_on:
    #   - postgres
    # environment:
    #   DATABASE_URL: postgres://postgres@postgres/rodnae
  # postgres:
  #   image: postgres:10.0-alpine
